// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm9g5a22pJcsazvbKdw38NSXC4iu7NSk8',
    appId: '1:966185730935:web:82b8ded2e26dd2f8a91772',
    messagingSenderId: '966185730935',
    projectId: 'authshield-91b56',
    authDomain: 'authshield-91b56.firebaseapp.com',
    storageBucket: 'authshield-91b56.firebasestorage.app',
    measurementId: 'G-HCB7NM708D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4rNPzjHxPOjUnUwpMrmEWuPD7CWQAZJI',
    appId: '1:966185730935:android:ec506dc1bfb02237a91772',
    messagingSenderId: '966185730935',
    projectId: 'authshield-91b56',
    storageBucket: 'authshield-91b56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsDKjkN6NXd08AdusRsPApxqhoxuMYNag',
    appId: '1:966185730935:ios:458240476c124599a91772',
    messagingSenderId: '966185730935',
    projectId: 'authshield-91b56',
    storageBucket: 'authshield-91b56.firebasestorage.app',
    iosBundleId: 'com.example.authshield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsDKjkN6NXd08AdusRsPApxqhoxuMYNag',
    appId: '1:966185730935:ios:458240476c124599a91772',
    messagingSenderId: '966185730935',
    projectId: 'authshield-91b56',
    storageBucket: 'authshield-91b56.firebasestorage.app',
    iosBundleId: 'com.example.authshield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm9g5a22pJcsazvbKdw38NSXC4iu7NSk8',
    appId: '1:966185730935:web:bcb80c29bfaaa440a91772',
    messagingSenderId: '966185730935',
    projectId: 'authshield-91b56',
    authDomain: 'authshield-91b56.firebaseapp.com',
    storageBucket: 'authshield-91b56.firebasestorage.app',
    measurementId: 'G-HPVM5GJPVR',
  );
}
